
FROM adoptopenjdk/openjdk17:alpine

WORKDIR /usr/src/app

COPY ./SkiStationProject-0.0.1-SNAPSHOT.jar /usr/src/app/SkiStationProject-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar", "SkiStationProject-0.0.1-SNAPSHOT.jar"]
