version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  jenkins-agent:
    image: jenkins/ssh-agent:jdk11
    container_name: jenkins-agent
    environment:
      - "JENKINS_AGENT_SSH_PUBKEY=<public_ssh_key_of_jenkins_master>"
    depends_on:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data:

